import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: "flex", justifyContent: "space-evenly", margin: "auto", padding: "10px", backgroundColor: "#ECEAE9" }}>

          <h2 style={{ fontSize: "20px" }}>
            <Link href="/firstframe">Theme Page</Link>
          </h2>
          <h2 style={{ fontSize: "20px" }}>
            <Link href="/thirdframe"> Dashboard</Link>
          </h2>
        </div>
        {children}
      </body>
    </html>
  );
}
